parameters:
  # Configuration for XBeteiligung connection

  # Expects the API endpoint base URL for the used xbeteiligung instance
  # Example: 172.0.0.1:9999
  addon_xbeteiligung_async_procedure_message_api_baseurl: ""
  # Auth token used for verifying the import request originated from
  # the expected Xbeteiligung instance
  addon_xbeteiligung_async_xbeteiligung_api_token: ""

  # XBeteiligung Async REST API authentication token
  addon_xbeteiligung_async_rest_authentication: ""

  # String to determine which type of procedure messages should be generated.
  # For Example: Kommunal, Raumordnung or Planfeststellung
  addon_xbeteiligung_async_procedure_message_type: ""

  # Use for incoming messages from rabbitMQ
  addon_xbeteiligung_async_enable_rabbitmq_communication: false

  # Maximum time in seconds we are allowed to rabbitMQ Message Broker
  addon_xbeteiligung_async_rabbitmq_communication_delay: 300

  addon_xbeteiligung_async_rabbitMqQueueName: 'XBeteiligungAddon'

  addon_xbeteiligung_async_rabbitMqRequestIdGet: 'XBeteiligung_Get'

  addon_xbeteiligung_async_rabbitMqRequestIdSend: 'XBeteiligung_Send'
