parameters:
  # Configuration for XBeteiligung connection

  # Expects the API endpoint base URL for the used xbeteiligung instance
  # Example: 172.0.0.1:9999
  xbeteiligung_procedure_message_api_baseurl: ""
  # Auth token used for verifying the import request originated from
  # the expected Xbeteiligung instance
  xbeteiligung_api_token: ""