# Linux Users: PHP Namespaces use back slash \ rather than a forward slash /
# So for destinations_php, the namespace would be TestNs\MyApp

xsd2php:
  namespaces:
    'http://xbeteiligung.de': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap'
    'http://xoev.de/latinchars/1_1/datatypes': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://xoev.de/schemata/code/1_0': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/datum/2': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.opengis.net/gml/3.2': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.w3.org/1999/xlink': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.xleitstelle.de/xbau/kernmodul/1/1': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/basisnachricht/5': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/behoerde/5': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/kommunikation/4': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/postanschrift/4': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/meldeanschrift/4': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/codes/gemeindeverzeichnis/3': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/auslandsanschrift/4': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/azrnummer/2': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/lichtbild/2': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/nachrichtentypen/5': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/allgemeinername/3': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/quittung/3': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/rueckweisung/4': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://www.osci.de/xinneres/weiterleitung/5': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'https://www.xleitstelle.de/xbeteiligung/1': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema'
    'http://xbeteiligung.de/V0103': 'DemosEurope\DemosplanAddon\XBeteiligung\Soap'

  destinations_php:
    'DemosEurope\DemosplanAddon\XBeteiligung\Soap': src/Soap
    'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema': src/Soap/schema

  destinations_jms:
    'DemosEurope\DemosplanAddon\XBeteiligung\Soap': src/Soap/metadata
    'DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema': src/Soap/metadata

  aliases:
    'http://www.w3.org/2001/XMLSchema':
      anySimpleType: 'DemosEurope\DemosplanAddon\XBeteiligung\Logic\XBeteiligungAnySimpleTypeHandler'
      anyType: 'Jms\Handler\GmlAnyTypeHandler'

  path_generator: psr4
  naming_strategy: long
