<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Db2BeteiligungBeteiligungPlanfeststellungAktualisierenNOK0272\Db2BeteiligungBeteiligungPlanfeststellungAktualisierenNOK0272AnonymousPHPType;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\NachrichteninhaltTemplateNOKTypeType;

/**
 * Class representing NachrichteninhaltAnonymousPHPType
 */
class NachrichteninhaltAnonymousPHPType extends NachrichteninhaltTemplateNOKTypeType
{
}

