<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Beteiligung2PlanungBeteiligungRaumordnungLoeschenNOK0329\Beteiligung2PlanungBeteiligungRaumordnungLoeschenNOK0329AnonymousPHPType;

/**
 * Class representing Beteiligung2PlanungBeteiligungRaumordnungLoeschenNOK0329
 *
 * Negative Quittierungsnachricht einer misserfolgten Aktualisierung des Beteiligungsverfahrens in der Beteiligungskomponente.
 */
class Beteiligung2PlanungBeteiligungRaumordnungLoeschenNOK0329 extends Beteiligung2PlanungBeteiligungRaumordnungLoeschenNOK0329AnonymousPHPType
{
}

