<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Beteiligung2PlanungBeteiligungKommunalAktualisierenNOK0422\Beteiligung2PlanungBeteiligungKommunalAktualisierenNOK0422AnonymousPHPType;

/**
 * Class representing Beteiligung2PlanungBeteiligungKommunalAktualisierenNOK0422
 *
 * Negative Quittierungsnachricht einer misserfolgten Aktualisierung des Beteiligungsverfahrens in der Beteiligungskomponente im Rahmen der kommunalen Bauleitplanung.
 */
class Beteiligung2PlanungBeteiligungKommunalAktualisierenNOK0422 extends Beteiligung2PlanungBeteiligungKommunalAktualisierenNOK0422AnonymousPHPType
{
}

