<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Beteiligung2PlanungBeteiligungPlanfeststellungLoeschenNOK0229\Beteiligung2PlanungBeteiligungPlanfeststellungLoeschenNOK0229AnonymousPHPType;

/**
 * Class representing Beteiligung2PlanungBeteiligungPlanfeststellungLoeschenNOK0229
 *
 * Negative Quittierungsnachricht einer misserfolgten Aktualisierung des Beteiligungsverfahrens in der Beteiligungskomponente.
 */
class Beteiligung2PlanungBeteiligungPlanfeststellungLoeschenNOK0229 extends Beteiligung2PlanungBeteiligungPlanfeststellungLoeschenNOK0229AnonymousPHPType
{
}

