<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Beteiligung2PlanungBeteiligungKommuneAktualisierenOK0412\Beteiligung2PlanungBeteiligungKommuneAktualisierenOK0412AnonymousPHPType;

/**
 * Class representing Beteiligung2PlanungBeteiligungKommuneAktualisierenOK0412
 *
 * Quittierungsnachricht einer erfolgten Aktualisierung des Beteiligungsverfahrens in der Beteiligungskomponente.
 */
class Beteiligung2PlanungBeteiligungKommuneAktualisierenOK0412 extends Beteiligung2PlanungBeteiligungKommuneAktualisierenOK0412AnonymousPHPType
{
}

