<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Beteiligung2PlanungBeteiligungPlanfeststellungAktualisierenOK0212\Beteiligung2PlanungBeteiligungPlanfeststellungAktualisierenOK0212AnonymousPHPType;

/**
 * Class representing Beteiligung2PlanungBeteiligungPlanfeststellungAktualisierenOK0212
 *
 * Quittierungsnachricht einer erfolgten Aktualisierung des Beteiligungsverfahrens in der Beteiligungskomponente.
 */
class Beteiligung2PlanungBeteiligungPlanfeststellungAktualisierenOK0212 extends Beteiligung2PlanungBeteiligungPlanfeststellungAktualisierenOK0212AnonymousPHPType
{
}

