<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Db2BeteiligungBeteiligungPlanfeststellungAktualisierenNOK0272\Db2BeteiligungBeteiligungPlanfeststellungAktualisierenNOK0272AnonymousPHPType;

/**
 * Class representing Db2BeteiligungBeteiligungPlanfeststellungAktualisierenNOK0272
 *
 * Diese negative Quittierungsnachricht wird nach einer erfolglosen Initiierung des Beteiligungsverfahrens von der Beteiligungskomponente an die Planungskomponente gesendet.
 */
class Db2BeteiligungBeteiligungPlanfeststellungAktualisierenNOK0272 extends Db2BeteiligungBeteiligungPlanfeststellungAktualisierenNOK0272AnonymousPHPType
{
}

