<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Db2BeteiligungBeteiligungPlanfeststellungAktualisierenOK0262\Db2BeteiligungBeteiligungPlanfeststellungAktualisierenOK0262AnonymousPHPType;

/**
 * Class representing Db2BeteiligungBeteiligungPlanfeststellungAktualisierenOK0262
 *
 * Quittierungsnachricht einer erfolgten Aktualisierung des Beteiligungsverfahrens in der Beteiligungskomponente.
 */
class Db2BeteiligungBeteiligungPlanfeststellungAktualisierenOK0262 extends Db2BeteiligungBeteiligungPlanfeststellungAktualisierenOK0262AnonymousPHPType
{
}

