<?php

namespace DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema;

use DemosEurope\DemosplanAddon\XBeteiligung\Soap\schema\Planung2BeteiligungBeteiligungPlanfeststellungAktualisieren0202\Planung2BeteiligungBeteiligungPlanfeststellungAktualisieren0202AnonymousPHPType;

/**
 * Class representing Planung2BeteiligungBeteiligungPlanfeststellungAktualisieren0202
 *
 * Diese Nachricht wird an die Beteiligungskomponente versendet und enthält die zur Aktualisierung des Beteiligungsverfahrens notwendigen Metadaten.
 */
class Planung2BeteiligungBeteiligungPlanfeststellungAktualisieren0202 extends Planung2BeteiligungBeteiligungPlanfeststellungAktualisieren0202AnonymousPHPType
{
}

